version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pethope_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: pethope@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/scripts/01_create_admin_user.sql:/docker-entrypoint-initdb.d/01_create_admin_user.sql
      - ./docker/scripts/02_create_usuario.sql:/docker-entrypoint-initdb.d/02_create_usuario.sql
      - ./docker/scripts/03_create_pet.sql:/docker-entrypoint-initdb.d/03_create_pet.sql

volumes:
  mysql_data: