spring:
  application:
    name: pethope
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pethope_db}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:pethope@123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
      format_sql: true  # Formata as queries para melhor legibilidade
      use_sql_comments: true  # Adiciona comentários explicativos no SQL gerado
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID:test}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET:secret}

server:
  servlet:
    context-path: /api

error:
  include-stacktrace: never
  include-message: never

logging:
  level:
    org.hibernate.SQL: DEBUG  # Exibe as consultas SQL
    org.hibernate.type.descriptor.sql: TRACE  # Mostra os valores dos parâmetros nas queries
    org.springframework.web: DEBUG  # Logs detalhados das requisições web
    org.springframework.security: DEBUG  # Logs detalhados do Spring Security
    org.hibernate.orm.jdbc.bind: TRACE