spring:
  application:
    name: pethope
  datasource:
      url: jdbc:mysql://localhost:3306/db_adote_me_api
      username: root
      password: '4633'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID:test}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET:secret}

server:
  servlet:
    context-path: /api

error:
  include-stacktrace: never
  include-message: never

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.web:
    org.springframework.security: INFO
    org.hibernate.orm.jdbc.bind: TRACE
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}