spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_adote_me_api
    username: root
    password: '@R0ot@8545'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 871356216202-asr2s8nvssnuejb1273nn6r58kptfrqe.apps.googleusercontent.com
            client-secret: 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

  application:
    name: pethope

server:
  servlet:
    context-path: /api

error:
  include-stacktrace: never
  include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health
